/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package eresto.View;

import eresto.Controller.KeranjangController;
import eresto.Model.Keranjang;
import java.awt.Container;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class PnlKeranjang extends javax.swing.JPanel {

    /**
     * Creates new form PnlKeranjang
     */
    public PnlKeranjang() {
        initComponents();
        getKeranjang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        tblKeranjang = new javax.swing.JTable();
        btnHapusKeranjang = new javax.swing.JButton();
        btnCheckout = new javax.swing.JButton();
        btnListTransaksi = new javax.swing.JButton();

        tblKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblKeranjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblKeranjangMousePressed(evt);
            }
        });
        jScrollPane6.setViewportView(tblKeranjang);

        btnHapusKeranjang.setBackground(new java.awt.Color(255, 51, 51));
        btnHapusKeranjang.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusKeranjang.setText("Hapus Keranjang");
        btnHapusKeranjang.setEnabled(false);
        btnHapusKeranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusKeranjangActionPerformed(evt);
            }
        });

        btnCheckout.setBackground(new java.awt.Color(51, 51, 51));
        btnCheckout.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckout.setText("Checkout");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        btnListTransaksi.setBackground(new java.awt.Color(153, 153, 153));
        btnListTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnListTransaksi.setText("Lihat Daftar Transaksi");
        btnListTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnListTransaksi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHapusKeranjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHapusKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnListTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblKeranjangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKeranjangMousePressed
        // TODO add your handling code here:
        btnHapusKeranjang.setEnabled(true);
    }//GEN-LAST:event_tblKeranjangMousePressed

    private void btnHapusKeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusKeranjangActionPerformed
        // TODO add your handling code here:
        // Mengambil keranjang id pada selected row di tblKeranjang
        int keranjang_id = Integer.parseInt((String)tblKeranjang.getModel().getValueAt(tblKeranjang.getSelectedRow(), 4));
        
        // memanggil delete()
        if (new KeranjangController().delete(keranjang_id)) {
            JOptionPane.showMessageDialog(this, "Successfully delete item from cart.", "Success", JOptionPane.INFORMATION_MESSAGE);
            getKeranjang();
        } else {
            JOptionPane.showMessageDialog(this, "Something Wrong.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusKeranjangActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        // TODO add your handling code here:
        // memvalidasi jika tblKeranjang kosong
        if (tblKeranjang.getModel().getRowCount() < 1) {
            JOptionPane.showMessageDialog(this, "Cart is empty.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // memanggil checkout()
        if (new KeranjangController().checkout()) {
            JOptionPane.showMessageDialog(this, "Checkout success.", "Success", JOptionPane.INFORMATION_MESSAGE);
            getKeranjang();
        } else {
            JOptionPane.showMessageDialog(this, "Something Wrong.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void btnListTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListTransaksiActionPerformed
        // TODO add your handling code here:
        // Mendapatkan kontainer induk (dialog) dari PnlKeranjang
        Container container = SwingUtilities.getAncestorOfClass(JDialog.class, PnlKeranjang.this);
        
        // Menutup dialog jika ditemukan
        if (container instanceof JDialog) {
            JDialog dialog = (JDialog) container;
            dialog.dispose();
        }
        
        // Membuka Option Dialog yang Isinya PnlTransaksi
        JOptionPane.showOptionDialog(
            null,
            new PnlTransaksi(),
            "List Transaksi",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.PLAIN_MESSAGE,
            null,
            new Object[]{}, // Agar buttonnya kosong
            null
        );
    }//GEN-LAST:event_btnListTransaksiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnHapusKeranjang;
    private javax.swing.JButton btnListTransaksi;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tblKeranjang;
    // End of variables declaration//GEN-END:variables

    private void getKeranjang() {
        // Mengambil data dari KeranjangController
        ArrayList<Keranjang> keranjang = new KeranjangController().getAllKeranjang();

        // Mendefinisikan kolom untuk tabel
        Object[] rows = {"Nama", "Jumlah", "Harga", "Subtotal", "ID"};

        // Membuat model tabel
        DefaultTableModel model = new DefaultTableModel(null, rows){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        // Mengatur model tabel untuk tabel tblKeranjang
        tblKeranjang.setModel(model);
        tblKeranjang.setRowHeight(20);

        // Mengisi tabel dengan data keranjang
        for (Keranjang item : keranjang) {
            String[] data = {item.getMenu_nama(), String.valueOf(item.getJumlah()), item.getHarga(), String.valueOf(item.getJumlah() * Integer.parseInt(item.getHarga())), String.valueOf(item.getId())};
            model.addRow(data);
        }

        // Menghapus kolom ID dari tampilan tabel
        tblKeranjang.removeColumn(tblKeranjang.getColumnModel().getColumn(4));

        // Menonaktifkan tombol Hapus Keranjang
        btnHapusKeranjang.setEnabled(false);
    }
}