/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package eresto.View;

import eresto.Controller.KeranjangController;
import eresto.Controller.MenuController;
import eresto.Model.Akun;
import eresto.Model.Keranjang;
import eresto.Model.Menu;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class PnlMinuman extends javax.swing.JPanel {

    /**
     * Creates new form PnlMinuman
     */
    public PnlMinuman() {
        initComponents();
        getMinuman();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        tblMinuman = new javax.swing.JTable();
        btnTambahKeranjang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        inputMinumanJumlah = new javax.swing.JSpinner();

        tblMinuman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblMinuman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblMinumanMousePressed(evt);
            }
        });
        jScrollPane6.setViewportView(tblMinuman);

        btnTambahKeranjang.setBackground(new java.awt.Color(51, 51, 51));
        btnTambahKeranjang.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahKeranjang.setText("Tambah Keranjang");
        btnTambahKeranjang.setEnabled(false);
        btnTambahKeranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahKeranjangActionPerformed(evt);
            }
        });

        jLabel1.setText("Jumlah :");

        inputMinumanJumlah.setEnabled(false);
        inputMinumanJumlah.setValue(1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTambahKeranjang)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputMinumanJumlah)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputMinumanJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTambahKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblMinumanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMinumanMousePressed
        // TODO add your handling code here:
        inputMinumanJumlah.setEnabled(true);
        btnTambahKeranjang.setEnabled(true);
    }//GEN-LAST:event_tblMinumanMousePressed

    private void btnTambahKeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahKeranjangActionPerformed
        // TODO add your handling code here:
        int menu_id = Integer.parseInt((String)tblMinuman.getModel().getValueAt(tblMinuman.getSelectedRow(), 3));
        int jumlah = Integer.parseInt(inputMinumanJumlah.getValue().toString());

        if (new KeranjangController().add(new Keranjang(0, Akun.getInstance().getId(), menu_id, jumlah))) {
            JOptionPane.showMessageDialog(this, "Successfully added to cart.", "Success", JOptionPane.INFORMATION_MESSAGE);
            getMinuman();
        } else {
            
        }
    }//GEN-LAST:event_btnTambahKeranjangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambahKeranjang;
    private javax.swing.JSpinner inputMinumanJumlah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tblMinuman;
    // End of variables declaration//GEN-END:variables
    
    private void getMinuman() {
        // Mengambil data dari MenuController untuk semua menu
        ArrayList<Menu> menu = new MenuController().getAllMenu();

        // Mendefinisikan kolom untuk tabel menu minuman
        Object[] rows = {"Nama", "Harga", "Stok", "ID"};

        // Membuat model tabel untuk menampilkan menu minuman
        DefaultTableModel model = new DefaultTableModel(null, rows){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        // Mengatur model tabel untuk tabel tblMinuman
        tblMinuman.setModel(model);
        tblMinuman.setRowHeight(20);

        // Mengisi tabel dengan data menu minuman
        for (Menu item : menu) {
            // Menambahkan baris hanya untuk menu dengan tipe 2 (minuman)
            if (item.getTipe() == 2) {
                String[] data = {item.getNama(), item.getHarga(), String.valueOf(item.getStok()), String.valueOf(item.getId())};
                model.addRow(data);
            }
        }

        // Menghapus kolom ID dari tampilan tabel
        tblMinuman.removeColumn(tblMinuman.getColumnModel().getColumn(3));

        // Mengatur nilai dan status komponen inputMinumanJumlah dan btnTambahKeranjang
        inputMinumanJumlah.setValue(1);
        inputMinumanJumlah.setEnabled(false);
        btnTambahKeranjang.setEnabled(false);
    }
}
